interface XYZ {
    readonly x: number;
    readonly y: number;
    readonly z: number;
    readonly x2: number;
    readonly y2: number;
    readonly z2: number;
    readonly radian: number;
    readonly angle: number;
    readonly size: number;
    readonly sum: number;
    readonly signature: XYZ;
    readonly unit: XYZ;
}
export declare function cross(a: XYZ, v: XYZ): XYZ;
export declare function dot(a: XYZ, v: XYZ): number;
export declare function add(a: XYZ, v: XYZ): XYZ;
export declare function sub(a: XYZ, v: XYZ): XYZ;
export declare function mul(a: XYZ, v: XYZ): XYZ;
export declare function div(a: XYZ, v: XYZ): XYZ;
export declare function equal(a: XYZ, v: XYZ): boolean;
export declare function xyz(x?: number | XYZ, y?: number, z?: number): XYZ;
export declare function vector(radian: number, force?: number): XYZ;
export declare function cube(v: number): XYZ;
declare const negone: XYZ;
declare const zero: XYZ;
declare const half: XYZ;
declare const one: XYZ;
declare const two: XYZ;
export { XYZ, negone, zero, half, one, two };
